# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared_pods
    pod 'Alamofire'
    pod 'FacebookCore'
    pod 'FacebookLogin'
    pod 'Firebase'
    pod 'Firebase/Auth'
    pod 'Firebase/Database'
    pod 'Firebase/Storage'
    pod 'GoogleSignIn'
    pod 'IGListKit', '~> 2.0.0'
    pod 'JSQMessagesViewController'
	pod 'Kingfisher'
	pod 'ObjectMapper'
	pod 'RxCocoa'
    pod 'RxOptional'
	pod 'RxSwift'
	pod 'Swarkn'
end

target 'InfiniteLoopers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InfiniteLoopers
  shared_pods

  target 'InfiniteLoopersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InfiniteLoopersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


