# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InfiniteLoopers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # Pods for InfiniteLoopers

	pod 'Alamofire'
	pod 'Firebase'
	pod 'Kingfisher'
	pod 'ObjectMapper'
	pod 'RealmSwift'
	pod 'RxCocoa'
	pod 'RxRealm'
	pod 'RxSwift'
	pod 'Swarkn'


  target 'InfiniteLoopersTests' do
    inherit! :search_paths
    pod 'Firebase'

  end

  target 'InfiniteLoopersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
